title = 'ziyi 的小屋'
baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'ananke'
copyright = ''
enableRobotsTXT = true
resourceDir = "../resources"

[params]
  AuthorNmae = 'liziyi'
  GitHubUser = 'liziyi-gh'
  background_color_class = "bg-black"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/liziyi-gh"

# [[params.ananke_socials]]
# name = "email"
# url = "592161867@qq.com"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
