title = 'ziyi 的小屋'
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

SectionPagesMenu = "main"
# this is set low for demonstrating with dummy content. Set to a higher number
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

# [languages]
#   # [languages.en]
#   #   title = "Ananke"
#   #   weight = 1
#   #   contentDir = "content/en"
#   # [languages.fr]
#   #   title = "Ananke Fr"
#   #   weight = 2
#   #   contentDir = "content/fr"
#   [languages.cn]
#     title = "Ananke"
#     weight = 1
#     # contentDir = ""

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[[params.ananke_socials]]
name = "email"
url = "592161867@qq.com"